[[main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link.
    title = ""
    weight = 1

[[main]]
    identifier = "series"
    pre = ""
    post = ""
    name = "series"
    url = "/series/"
    title = ""
    weight = 2

[[main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "about"
    url = "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    title = ""
    weight = 3

[[main]]
    identifier = "contact"
    pre = "<i class='fas fa-envelope fa-fw'></i>"
    post = ""
    name = ""
    url = "mailto:veb@thel.foo"
    title = ""
    weight = 4

[[main]]
    identifier = "youtube"
    pre = "<i class='fab fa-youtube fa-fw'></i>"
    post = ""
    name = ""
    url = "https://www.youtube.com/@Thel-foo"
    title = ""
    weight = 5
[[main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    post = ""
    name = ""
    url = "https://github.com/vebbis321"
    title = ""
    weight = 6

